{% set name = "geomeTRIC" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leeping/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9a1d9172ae309cebb8720de806de31770f8e1e74e25c64b15a6022cc9cd6579d

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - geometric-optimize = geometric.optimize:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - numpy
    - networkx
    - six
    - scipy

test:
  imports:
    - geometric
  requires:
    - pytest
    - rdkit
    - openmm
    - ase
    - xtb-python
    - python {{ python_min }}
  commands:
    - $PYTHON -m pytest --pyargs geometric -v -k json

about:
  home: http://github.com/leeping/geomeTRIC/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Molecular geometry optimizer in the TRIC coordinate system.'
  dev_url: http://github.com/leeping/geomeTRIC/

extra:
  recipe-maintainers:
    - leeping
    - dgasmith
    - yudongqiu
    - j-wags
    - bennybp
    - loriab
